CREATE OR REPLACE FILE FORMAT MARKET_CSV_FORMAT TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"';
CREATE OR REPLACE STAGE MARKET_STAGE FILE_FORMAT = MARKET_CSV_FORMAT;
PUT 'file:///opt/project/data/warehouse/Dim_Stocks.csv' @MARKET_STAGE AUTO_COMPRESS=TRUE OVERWRITE=TRUE;
COPY INTO DIM_STOCKS FROM @MARKET_STAGE/Dim_Stocks.csv.gz FILE_FORMAT=(FORMAT_NAME=MARKET_CSV_FORMAT) ON_ERROR='CONTINUE';
PUT 'file:///opt/project/data/warehouse/Dim_Date.csv' @MARKET_STAGE AUTO_COMPRESS=TRUE OVERWRITE=TRUE;
COPY INTO DIM_DATE FROM @MARKET_STAGE/Dim_Date.csv.gz FILE_FORMAT=(FORMAT_NAME=MARKET_CSV_FORMAT) ON_ERROR='CONTINUE';
PUT 'file:///opt/project/data/warehouse/Fact_Market_Trades.csv' @MARKET_STAGE AUTO_COMPRESS=TRUE OVERWRITE=TRUE;
COPY INTO FACT_MARKET_TRADES FROM @MARKET_STAGE/Fact_Market_Trades.csv.gz FILE_FORMAT=(FORMAT_NAME=MARKET_CSV_FORMAT) ON_ERROR='CONTINUE';