CREATE DATABASE IF NOT EXISTS FINANCE_DB;
USE DATABASE FINANCE_DB;
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE SCHEMA IF NOT EXISTS MARKET_ANALYTICS;
USE SCHEMA MARKET_ANALYTICS;

CREATE OR REPLACE TABLE DIM_STOCKS (
    TICKERID INTEGER,
    SYMBOL STRING,
    COMPANYNAME STRING
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATEID INTEGER,
    FULLDATE DATE,
    YEAR INTEGER,
    MONTH INTEGER,
    DAY INTEGER
);

CREATE OR REPLACE TABLE FACT_MARKET_TRADES (
    TRADEID INTEGER,
    TICKERID INTEGER,
    DATEID INTEGER,
    OPENPRICE FLOAT,
    CLOSEPRICE FLOAT,
    VOLUME FLOAT,
    MA_7 FLOAT,
    RSI FLOAT
);